sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpython-dev
  - sudo apt-get install -y libgoogle-glog-dev 
  - sudo apt-get install -y libatlas-base-dev
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libsuitesparse-dev
  - mkdir build
  - cd build
  - cmake ..

script: make


