sudo: required

dist: trusty

language: cpp

compiler:
  - gcc
  # - clang

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y libpython-dev
  - sudo apt-get install -y libgoogle-glog-dev 
  - sudo apt-get install -y libatlas-base-dev
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libsuitesparse-dev
  - wget http://ceres-solver.org/ceres-solver-1.11.0.tar.gz -O /tmp/ceres-solver-1.11.0.tar.gz
  - tar -C /tmp -xzvf /tmp/ceres-solver-1.11.0.tar.gz
  - rm /tmp/ceres-solver-1.11.0.tar.gz
  - mkdir /tmp/ceres-solver-1.11.0-build
  - cd /tmp/ceres-solver-1.11.0-build
  - cmake /tmp/ceres-solver-1.11.0 && make && sudo make install

before_script:
  - mkdir /tmp/game-build
  - cd /tmp/game-build

script:
  - cmake $TRAVIS_BUILD_DIR
  - make -j4

